### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by BhaskarTrivedi** [openai/doom-py#14]
python setup.py build
running build
Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    include_package_data=True,
  File "C:\Users\bhask\Anaconda3\envs\tensorflow\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\bhask\Anaconda3\envs\tensorflow\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\bhask\Anaconda3\envs\tensorflow\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\bhask\Anaconda3\envs\tensorflow\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 63, in run
    build_func()
  File "setup.py", line 45, in build_windows
    build_common('dll')
  File "setup.py", line 23, in build_common
    python_library = find_python_library()
  File "setup.py", line 16, in find_python_library
    python_library = os.path.join(sysconfig.get_config_var(var), 'libpython{}.{}'.format(sysconfig.get_python_version(), dynamic_library_extension))
  File "C:\Users\bhask\Anaconda3\envs\tensorflow\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by BhaskarTrivedi** [comment]
Issue was due to library path was empty, i manually updated setup.py 
#python_library = os.path.join(sysconfig.get_config_var(var), 'libpython{}.{}'.format(sysconfig.get_python_version(), dynamic_library_extension))
to
python_library = os.path.join("C:\\Users\\XXX\\Anaconda3\\envs\\tensorflow\\libs", 'libpython{}.{}'.format(sysconfig.get_python_version(), dynamic_library_extension)
..
Adding hard coded value is not solution I will left it to developer if they want to close it.
