### ISSUE TITLE
setup build failed on ubuntu 18.04 server  

### ISSUE THREAD

**Issue by BhaskarTrivedi** [openai/doom-py#15]
python setup.py build
running build
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   date_time
--   chrono
--   regex
--   iostreams
--   atomic
CMake Deprecation Warning at cmake_modules/CreateLaunchers.cmake:48 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  src/vizdoom/CMakeLists.txt:13 (include)

-- Could NOT find GME (missing: GME_INCLUDE_DIR) 
-- Using system zlib
-- Using system jpeg library
-- Using system bzip2 library
-- Using internal gme library
-- /usr/include
-- /usr/include
-- /home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/vizdoom/lzma/C
-- Could not find FMOD include files
-- Selected assembler: /usr/bin/as
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
--   atomic
-- Fluid synth libs: /usr/lib/x86_64-linux-gnu/libfluidsynth.so
-- Found PythonInterp: /home/bhaskartrivedi/anaconda3/envs/worldmodel/bin/python (found suitable version "3.5.4", minimum required is "2.7") 
-- Found PythonInterp: /home/bhaskartrivedi/anaconda3/envs/worldmodel/bin/python (found suitable version "3.5.4", minimum required is "3") 
-- Using python library: /home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/libpython3.5m.so
-- Using python include: /home/bhaskartrivedi/anaconda3/envs/worldmodel/include/python3.5m
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1628 (message):
  No header defined for python-py354; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:126 (find_package)

-- Could NOT find Boost
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1628 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)

-- Could NOT find Boost
-- Boost library python-py35: 
-- Could NOT find Boost
-- Boost library python35: 
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1628 (message):
  No header defined for python-py3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)

-- Could NOT find Boost
-- Boost library python-py3: 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python3
-- Boost library python3: /usr/lib/x86_64-linux-gnu/libboost_python3.so
-- Found components for NumPy
-- NUMPY_ROOT_DIR    = /usr/local
-- NUMPY_INCLUDES    = /home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/site-packages/numpy/core/include
-- NUMPY_LIBRARIES   = /home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/site-packages/numpy/core/lib/libnpymath.a
-- NUMPY_API_VERSION = 1.15.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bhaskartrivedi/WorldModel/doom-py-master/doom_py
[  0%] Built target lemon
[  0%] Built target arithchk
[  0%] Built target freedoom2
[  0%] Built target updaterevision
[  1%] Building CXX object CMakeFiles/libvizdoom_shared.dir/src/lib/ViZDoomGame.cpp.o
[  2%] Built target re2c
[  5%] Built target lzma
[  5%] Building CXX object CMakeFiles/libvizdoom_static.dir/src/lib/ViZDoomGame.cpp.o
[ 21%] Built target dumb
[ 30%] Built target gme
[ 31%] Built target qnan
[ 32%] Built target zipdir
[ 33%] Built target gdtoa
[ 97%] Built target vizdoom
[ 97%] Generating ../../../bin/vizdoom.pk3
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/vizdoom/../../bin/vizdoom.pk3 contains 583 files (updated 0)
[ 97%] Built target pk3
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp: In member function ‘bool vizdoom::DoomGame::loadConfig(std::__cxx11::string)’:
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:743:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax erorr in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:743:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax erorr in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:757:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty key in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:757:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty key in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:784:30: error: ‘cerr’ is not a member of ‘std’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_buttons[i]<<". Lines ignored.\n";
                              ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:784:30: note: suggested alternative: ‘erf’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_buttons[i]<<". Lines ignored.\n";
                              ^~~~
                              erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:789:26: error: ‘cerr’ is not a member of ‘std’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:789:26: note: suggested alternative: ‘erf’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
                          erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:815:30: error: ‘cerr’ is not a member of ‘std’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_variables[i]<<". Lines ignored.\n";
                              ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:815:30: note: suggested alternative: ‘erf’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_variables[i]<<". Lines ignored.\n";
                              ^~~~
                              erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:820:26: error: ‘cerr’ is not a member of ‘std’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:820:26: note: suggested alternative: ‘erf’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
                          erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:837:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". \"+=\" is not supported for non-list properties. Line #"<<line_number<<" ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:837:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". \"+=\" is not supported for non-list properties. Line #"<<line_number<<" ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:846:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty value in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:846:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty value in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:871:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsigned int value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:871:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsigned int value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:888:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Float value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:888:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Float value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:953:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Boolean value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:953:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Boolean value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:983:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". (ASYNC_)SPECTATOR || PLAYER expected instead of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:983:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". (ASYNC_)SPECTATOR || PLAYER expected instead of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1012:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1012:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1017:18: error: ‘cerr’ is not a member of ‘std’
             std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported key: "<<key<<" in line #"<<line_number<<". Line ignored.\n";
                  ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1017:18: note: suggested alternative: ‘erf’
             std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported key: "<<key<<" in line #"<<line_number<<". Line ignored.\n";
                  ^~~~
                  erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp: In member function ‘bool vizdoom::DoomGame::loadConfig(std::__cxx11::string)’:
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:743:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax erorr in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:743:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax erorr in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:757:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty key in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:757:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty key in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:784:30: error: ‘cerr’ is not a member of ‘std’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_buttons[i]<<". Lines ignored.\n";
                              ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:784:30: note: suggested alternative: ‘erf’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_buttons[i]<<". Lines ignored.\n";
                              ^~~~
                              erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:789:26: error: ‘cerr’ is not a member of ‘std’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:789:26: note: suggested alternative: ‘erf’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
                          erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:815:30: error: ‘cerr’ is not a member of ‘std’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_variables[i]<<". Lines ignored.\n";
                              ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:815:30: note: suggested alternative: ‘erf’
                         std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value in lines "<<start_line<<"-"<<line_number<<": "<<str_variables[i]<<". Lines ignored.\n";
                              ^~~~
                              erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:820:26: error: ‘cerr’ is not a member of ‘std’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:820:26: note: suggested alternative: ‘erf’
                     std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Syntax error in lines "<<start_line<<"-"<<line_number<<". Lines ignored.\n";
                          ^~~~
                          erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:837:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". \"+=\" is not supported for non-list properties. Line #"<<line_number<<" ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:837:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". \"+=\" is not supported for non-list properties. Line #"<<line_number<<" ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:846:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty value in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:846:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Empty value in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:871:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsigned int value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:871:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsigned int value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:888:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Float value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:888:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Float value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:953:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Boolean value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:953:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Boolean value expected insted of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:983:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". (ASYNC_)SPECTATOR || PLAYER expected instead of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:983:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". (ASYNC_)SPECTATOR || PLAYER expected instead of: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1012:22: error: ‘cerr’ is not a member of ‘std’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1012:22: note: suggested alternative: ‘erf’
                 std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported value: "<<raw_val<<" in line #"<<line_number<<". Line ignored.\n";
                      ^~~~
                      erf
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1017:18: error: ‘cerr’ is not a member of ‘std’
             std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported key: "<<key<<" in line #"<<line_number<<". Line ignored.\n";
                  ^~~~
/home/bhaskartrivedi/WorldModel/doom-py-master/doom_py/src/lib/ViZDoomGame.cpp:1017:18: note: suggested alternative: ‘erf’
             std::cerr<<"WARNING! Loading config from: \""<<filename<<"\". Unsupported key: "<<key<<" in line #"<<line_number<<". Line ignored.\n";
                  ^~~~
                  erf
CMakeFiles/libvizdoom_shared.dir/build.make:110: recipe for target 'CMakeFiles/libvizdoom_shared.dir/src/lib/ViZDoomGame.cpp.o' failed
make[2]: *** [CMakeFiles/libvizdoom_shared.dir/src/lib/ViZDoomGame.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/libvizdoom_shared.dir/all' failed
make[1]: *** [CMakeFiles/libvizdoom_shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/libvizdoom_static.dir/build.make:110: recipe for target 'CMakeFiles/libvizdoom_static.dir/src/lib/ViZDoomGame.cpp.o' failed
make[2]: *** [CMakeFiles/libvizdoom_static.dir/src/lib/ViZDoomGame.cpp.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/libvizdoom_static.dir/all' failed
make[1]: *** [CMakeFiles/libvizdoom_static.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Could not build doom-py: Command '['make', '-j', '35']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Try running 'apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip'

Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    include_package_data=True,
  File "/home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 63, in run
    build_func()
  File "setup.py", line 41, in build_linux
    build_common('so')
  File "setup.py", line 29, in build_common
    subprocess.check_call(['make', '-j', str(cores_to_use)], cwd='doom_py')
  File "/home/bhaskartrivedi/anaconda3/envs/worldmodel/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '35']' returned non-zero exit status 2

**Comment by MrDadaGuy** [comment]
Same issue for me... any progress?

**Comment by BhaskarTrivedi** [comment]
> Same issue for me... any progress?

Nope i switched to other work..

**Comment by robin7g** [comment]
Same error here building on desktop ubuntu 18.04.1 

It appears other libraries are updating around doom-py with changes and now doom-py won't build. This error above is caused by the inclusion order of  **iostream**   

If you add
 
`#include <iostream>`

at the top of **../doom_py/src/lib/VizDoomGame.cpp**  it will get further in the build. 

This is just the first problem. It will then fail because **boost** library has updated as of 1.65+ and no longer has boost::python::numeric module it has been replaced by boost::python::numpy.  The contents of these modules has changed so its not a simple replacement. This looks like a rabbit hole! 

Current error is 
`/ViZDoomGamePython.cpp:29:26: **error**: ‘boost::python::numeric’ has not been declared`

**Comment by robin7g** [comment]
If you are using boost v1.65+ take a look at the code changes here. Worked for me.

https://github.com/robin7g/doom-py/pull/1/files

**Comment by leilani-x** [comment]
> If you are using boost v1.65+ take a look at the code changes here. Worked for me.
> 
> https://github.com/robin7g/doom-py/pull/1/files

@robin7g Thanks. This worked for me too. But when I import doom_py in python3, I get the following error: 

> from doom_py.vizdoom import * 
> ImportError: /home/x/package/doom-py/doom_py/vizdoom.so: undefined symbol: _ZN5boost6python6detail11init_moduleEPKcPFvvE

When I import doom_py in python3, I get this:

> ImportError: doom_py/vizdoom.so: undefined symbol: _ZNK5boost6python5numpy7ndarray4copyEv

**Comment by modrzywolski** [comment]
The problem exists also on Ubuntu 20.04

The file ViZDoomGamePython.cpp uses boost::python::numpy and there seems to be missing library boost_numpy38 in Boost_LIBRARIES

So basically I hacked doom_py/CMakeLists.txt and added  boost_numpy38 to VIZDOOM_LIBS

It is not a proper solution but at least hint for real fix.
